Lesson 6 acceptance testing
popeskul/qna pull request #3
Opened 2021-07-18 14:48 UTC by popeskul

2021-07-22 10:09 UTC, vkurennov requested changes

2021-07-22 10:09 UTC, vkurennov commented on app/views/questions/index.html.slim
> +- unless questions.nil?
тут лучше метод `empty?` использовать, потому что пустая коллекция != nil

2021-07-22 10:09 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
где тесты на destroy?
привыкай к TDD: прежде чем писать какой-то код, у тебя должен появиться тест ("красный"), который потребует наличие этого кода

2021-07-22 10:09 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
здесь должно быть 2 контекста: для автора и для не-автора

2021-07-22 10:09 UTC, vkurennov commented on spec/features/answer/user_can_answer_the_question_spec.rb
> +      expect(page).to have_content 'The question was created successfully.'
нужно проверить еще и наличе самого текста ответа на странице

2021-07-22 10:09 UTC, vkurennov commented on spec/features/answer/user_can_answer_the_question_spec.rb
> +    expect(page).to have_content "Body can't be blank"
наверное, если незалогиненный юзер пытается создать ответ (а у него таких прав быть не должно), то поведение должно быть иным, чем валидация. что, если юзер введет не пустой ответ, какое тогда должно быть повдеение системы? Вот это и надо тестировать. Либо то, что юзер вообще не видит формы ответа

2021-07-22 10:09 UTC, vkurennov commented on spec/features/answer/user_can_delete_answer_spec.rb
> +    answer = create(:answer, question: question)
это  вынести в let

2021-07-22 10:09 UTC, vkurennov commented on spec/features/answer/user_can_delete_answer_spec.rb
> +    visit answer_path(answer)
удаление должно со страницы вопроса происходить, не должно быть отдельной страницы для ответа

2021-07-22 10:09 UTC, vkurennov commented on spec/features/answer/user_can_delete_answer_spec.rb
> +    expect(page).to have_no_content answer.body
перед удалением надо проверить, что такое ответ есть на странице

2021-07-22 10:09 UTC, vkurennov commented on spec/features/answer/user_can_delete_answer_spec.rb
> +    expect(page).to have_no_link('Delete', href: answer_path(answer))
конечно ее там нет, т.к. ссылки на удаление у тебя на странице ответа. то есть ты на разные страницы заходишь и проверяшь разное поведение. а надо проверять разное поведение для разных типов пользователей **на одной и той же странице**

2021-07-22 10:09 UTC, vkurennov commented on spec/features/answer/user_can_delete_answer_spec.rb
> +    expect(page).to have_no_link('Delete', href: answer_path(answer))
тут еще веселее: ты проверяешь отсутсвие ссылки, вообще не заходя ни на какую страницу, видимо на главной. у тебя начальные действия для всех сценариев одинаковые почти: создаем ответ, заходим на одну и ту же страницу вопроса, но под разными юзерами (автор, не-автор, не залогинен)

2021-07-22 10:09 UTC, vkurennov commented on spec/features/question/user_can_delete_his_question_spec.rb
> +    scenario 'Authenticated user can delete his question' do
а еще нужны сценарии для не-автора и для незалогиненного юзера

2021-07-22 10:09 UTC, vkurennov commented on spec/features/question/user_can_delete_his_question_spec.rb
> +      question = create(:question, author: user)
это в let

2021-07-22 10:09 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
где тесты на метод проверки автора?

2021-07-22 12:40 UTC, popeskul commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
поправил

2021-07-22 12:41 UTC, popeskul commented on spec/features/question/user_can_delete_his_question_spec.rb
> +      question = create(:question, author: user)
поправил

2021-07-22 20:43 UTC, popeskul commented on app/models/user.rb
> +    obj.author.id == self.id
Поправил

2021-07-22 21:14 UTC, popeskul commented on app/views/answers/show.html.slim
> += answer.id
поправил

2021-07-22 21:15 UTC, popeskul commented on app/views/answers/show.html.slim
> += link_to 'Delete answer', answer_path(answer), method: :delete
поправил

2021-07-22 21:28 UTC, popeskul commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
добавил

2021-07-22 21:47 UTC, popeskul commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
добавил

2021-07-22 21:52 UTC, popeskul commented on spec/features/answer/user_can_answer_the_question_spec.rb
> +      expect(page).to have_content 'The question was created successfully.'
поправил

2021-07-22 22:00 UTC, popeskul commented on spec/features/question/user_can_delete_his_question_spec.rb
> +    scenario 'Authenticated user can delete his question' do
добавил

2021-07-22 22:09 UTC, popeskul commented on spec/features/answer/user_can_delete_answer_spec.rb
> +    answer = create(:answer, question: question)
@vkurennov тут не вынести в let

2021-07-22 22:19 UTC, popeskul commented on spec/features/answer/user_can_delete_answer_spec.rb
> +    expect(page).to have_no_content answer.body
поправил

2021-07-22 22:21 UTC, popeskul commented on spec/features/answer/user_can_delete_answer_spec.rb
> +    expect(page).to have_no_link('Delete', href: answer_path(answer))
поправил

2021-07-22 22:21 UTC, popeskul commented on spec/features/answer/user_can_delete_answer_spec.rb
> +    expect(page).to have_no_link('Delete', href: answer_path(answer))
поправил

2021-07-22 22:53 UTC, popeskul commented on spec/features/answer/user_can_answer_the_question_spec.rb
> +    expect(page).to have_content "Body can't be blank"
исправил

2021-07-22 22:55 UTC, popeskul commented on spec/features/answer/user_can_delete_answer_spec.rb
> +    visit answer_path(answer)
поправил

2021-07-23 08:50 UTC, vkurennov requested changes

2021-07-23 08:50 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question
тут тоже можно использовать `@answer.question` и вынести таким образом редирект из условия, т.к. они одинаковые получатся

2021-07-23 08:50 UTC, vkurennov commented on app/views/questions/_answer.html.slim
> += answer.id
id  - эт внутренняя информация и может не совпадать с порядковым номером, ее лучше не показывать пользователю (никогда), а если нужна нумерация, то делать ее вручную (через each_with_index, например)

2021-07-23 08:50 UTC, vkurennov commented on config/routes.rb
> +  resources :questions, shallow: true do
если у корневого ресурса указана опция shallow, то это означает, что она применяется ко всем вложенным, т.е. у answers эту опцию указывать уже не нужно

2021-07-23 08:50 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete_answer }.to change(question.answers, :count).by(-1)
тут в change лучше указывать просто Answer, т.к. ассоциации при удалении не важны

2021-07-23 08:50 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete_answer }.to_not change(question.answers, :count)
здесь тоже лучше просто Answer в change

2021-07-23 08:50 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
нет, не добавил. ты это сделал для ответов, но здес-то тест контроллера вопросов и здесь тоже нужно тестировать вариант для автора и для не-автора, ты же разные контроллеры тестируешь

2021-07-23 08:50 UTC, vkurennov commented on spec/features/answer/user_can_answer_the_question_spec.rb
> +      expect(page).to have_content 'You need to sign in or sign up before continuing.'
и тут хорошо бы проверить, что ответа на странице при этом нет

2021-07-23 08:50 UTC, vkurennov commented on spec/features/answer/user_can_delete_answer_spec.rb
> +      answer = create(:answer, question: question, author: user)
не надо в тестах данные создавать, выноси их в let, если объект нужен перед тестом, то можноиспользовать `let!`

2021-07-23 08:50 UTC, vkurennov commented on spec/features/answer/user_can_delete_answer_spec.rb
> +      click_link href: answer_path(answer)
так не совсем очевидно, что это за ссылка. лучше через `within` ограничить нужную область страницы и клик делать по имени ссылки ('Delete')

2021-07-23 08:50 UTC, vkurennov commented on spec/features/answer/user_can_delete_answer_spec.rb
> +      expect(page).to have_content 'Answer was successfully deleted'
и надо проверить, что самого ответа больше нет на странице, это важнее, чем сообщение

2021-07-23 08:50 UTC, vkurennov commented on spec/features/question/user_can_delete_his_question_spec.rb
> +    scenario "Authenticated user can not delete another''s question" do
и нужен еще сценарий для незалогиненного юзера

2021-07-23 08:50 UTC, vkurennov commented on spec/models/user_spec.rb
> +    context 'answer' do
достатчоно на одном объекте проверить, метод ведь универсальный и зависит только от наличия атрибута author_id

2021-07-23 09:30 UTC, popeskul commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
добавил

2021-07-23 10:56 UTC, popeskul commented on spec/features/answer/user_can_delete_answer_spec.rb
> +      click_link href: answer_path(answer)
find_link('Delete answer', href: answer_path(answer)).click

2021-07-23 13:22 UTC, vkurennov approved these changes

2021-07-23 14:23 UTC, merged