Lesson 10: vote with concerns
popeskul/qna pull request #8
Opened 2021-08-08 10:52 UTC by popeskul

Vote model: 
- [ ]  implement concerns for vote (Votable)
- [ ]  user can vote up
- [ ]  user can vote down
- [ ]  user can un vote
- [ ]  user can see resulting rating
- [ ]  user can vote "for" or "against" a specific question / answer only once

Vote controller:
- [ ] implement concerns for vote (Voted)
- [ ] authenticated user can vote for their favorite question / answer
- [ ] user can't vote for their question / answer
- [ ] user can vote "for" or "against" a specific question / answer only once
- [ ] user can cancel his vote and then re-vote
- [ ] user can see resulting rating

2021-08-10 10:17 UTC, vkurennov requested changes

2021-08-10 10:17 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    render error_response('You have already voted earlier') if @votable.exists_user?(@votable)
какой-то странный вызов метода `exists_user?`, он и так вызывается у @votable, зачем его еще раз передавать в метод? логично тогда уж юзера и передавать. Да и название метода лучше переименовать во что-то вроде `voted?`, тогда вызов будет вида `@votable.voted_by?(current_user)` что довольно однозначно читается.

2021-08-10 10:17 UTC, vkurennov commented on app/models/concerns/Votable.rb
> +  def exists_user?(user)
так, судя по сигнатуре у тебя и передается юзер в этот метод, что логично, почему тогда в контроллере у тебя сюда передается @votable?

2021-08-10 10:17 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    render error_response('You have already voted earlier') if @votable.exists_user?(@votable)
у тебя неверный вызов здесь и в 30й строке, не тот аргумент передаешь методу, а значит, тесты не показали тебе эту ошибку. Надо дописать тесты так, чтобы они ее воспроизводили и потом поправить код

2021-08-10 10:17 UTC, vkurennov commented on spec/controllers/concerns/voted.rb
> +shared_examples 'voted' do
а где тесты на экшн un_vote?

2021-08-10 10:17 UTC, vkurennov commented on spec/controllers/concerns/voted.rb
> +    describe 'Authorized user' do
есть еще кейс не покрытый тестами: когда юзер уже проголосовал, в нем как раз у тебя и ошибка в контроллере

2021-08-10 10:17 UTC, vkurennov commented on spec/features/answer/user_can_vote_for_answer_spec.rb
> +feature 'Vote for answer', %(
тут тоже нужен сценарий, когда юзер повторно не может голосовать

2021-08-10 10:17 UTC, vkurennov commented on spec/features/question/user_can_vote_for_question_spec.rb
> +feature 'Vote for question', %(
тут то же самое

2021-08-10 10:17 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    render error_response('You have already voted earlier') if @votable.exists_user?(@votable)
здесь тоже не верный аргумент у метода `exists_user?`

2021-08-10 17:07 UTC, popeskul commented on spec/controllers/concerns/voted.rb
> +    describe 'Authorized user' do
Теперь если пользователь пытается постать второй раз, тогда ничего не поменяется

2021-08-10 17:54 UTC, popeskul commented on app/controllers/concerns/voted.rb
> +    render error_response('You have already voted earlier') if @votable.exists_user?(@votable)
исправил

2021-08-11 10:13 UTC, vkurennov approved these changes

2021-08-11 11:33 UTC, merged