Lesson 11 action cable
popeskul/qna pull request #9
Opened 2021-08-18 12:54 UTC by popeskul

2021-08-25 11:40 UTC, vkurennov requested changes

2021-08-25 11:40 UTC, vkurennov commented on app/channels/answers_channel.rb
> +    stream_from 'answers'
так у тебя будет один стрим вообще на все ответы, вне зависимости от вопроса, что не очень хорошо

2021-08-25 11:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +        locals: { answer: @answer, current_user: current_user }
вот это неверно, потому что ты таким образом отправишь шаблон, который видит автор, со ссылками на удаление и т.п. Потому что current_user на сервере - это тот, кто сделал запрос, а ты потом неизвестному кругу подписчиков ответ отсылаешь. Надо автору отдавать обычный js-овета, как ранее, а остальным можно через AC отправлять упрощенный шаблон без ссылок на редактирование и прочее. Или отправлять json и шабон формировать уже на клиенте.

2021-08-25 11:40 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +        locals: { question: @question, current_user: current_user }
см замечание к ответам, тут то же самое

2021-08-25 12:46 UTC, popeskul commented on app/channels/answers_channel.rb
> +    stream_from 'answers'
Теперь отсылаю по question_id

2021-08-30 08:35 UTC, vkurennov approved these changes

2021-08-30 19:17 UTC, merged